### ISSUE TITLE
[feat] Option to use `sass-embedded` to speed up compilation

### ISSUE THREAD

**Issue by maxiruani** [glromeo/esbuild-sass-plugin#100]
I would like to have an option to use [sass-embedded](https://github.com/sass/embedded-host-node) instead to compile files.
It suppose to be [faster](https://github.com/sass/dart-sass/blob/main/perf.md) than `sass` package and a "drop-in" replacement.

According to documentation, it provides the same JavaScript API but unlike `sass` package, the asynchronous API in `sass-embedded` will generally be faster than the synchronous API.

This feature would be very nice mainly for development env and improve DX.

**Comment by glromeo** [comment]
Sorry Max, we have explored that possibility with poor results... the way esbuild the plugin and sass interact lead to a performance degradation which is ultimately due to Js in the middle
https://github.com/glromeo/esbuild-sass-plugin/pull/71

**Comment by maxiruani** [comment]
Oops! Sorry to hear that (and for not checking previous issues haha). I was looking for alternatives to make compilation faster, I have also found [grass](https://github.com/connorskees/grass) (a rust based sass compiler, still in progress). Have you already analyzed this alternative in the past? I haven't have the chance to test its performance yet.

**Comment by glromeo** [comment]
In that "due to Js in the middle" I am trying to condense the experience I got out of those experiments.
Crossing languages/runtimes means bottlenecks, esbuild does a great job at optimizing the go/js but once you jumped once it's best if you stick to js because otherwise you end up chaining further jumps without possibility of concurrency.
