### ISSUE TITLE
`cache` does not track dependencies on other files

### ISSUE THREAD

**Issue by Minnozz** [glromeo/esbuild-sass-plugin#11]
Example:
* Cache is enabled by passing a `Map` to the `cache` option 
* `entry.scss` imports `bar.scss`
* After the initial build, `bar.scss` is changed
* An incremental build is started
* `transform` is called for `entry.scss`
* `entry.scss` is in the cache and that file itself has not been changed, so the cached transform result with the old contents of `bar.scss` is returned
* The cache is never queried for `bar.scss`
* The old contents of `bar.scss` end up in the bundle

**Comment by Minnozz** [comment]
It seems like this case is described in the [esbuild docs](https://esbuild.github.io/plugins/#caching-your-plugin):
>  Cache invalidation only works if slowTransform() is a pure function (meaning that the output of the function only depends on the inputs to the function) and if all of the inputs to the function are somehow captured in the lookup to the cache map. For example if the transform function automatically reads the contents of some other files and the output depends on the contents of those files too, then the cache would fail to be invalidated when those files are changed because they are not included in the cache key.

**Comment by glromeo** [comment]
Hi Bart, thank you for pointing this out... 
sass gives me the files that I should track and as of now I pass those on to esbuild. 
I was expecting it to magically deal with dependencies but thinking it twice it's not its task!
I could check not just the main file but also the dependencies using fs.stat but I would like to find a way to make the cache better than it is right now rather than worse off in terms of performance.
So I'd rather asynchronously clear the entries when a change is detected in the fs.
It would be amazing if, given esbuild does the polling, I could hook into it to get the notification I want because otherwise I might end up with asynchronous issues... 
I am looking into this and I hope I can come up with a fix soon!

**Comment by glromeo** [comment]
Hi Bart
version v1.4.1 should have (I hope) fixed the cache issue with sass imports
let me know how it goes

**Comment by glromeo** [comment]
At the end the fix I applied is to check for all the imported file mtimes so it should work regardless of watch mode

**Comment by Minnozz** [comment]
Seems to work with your fix, thanks for the quick update!
