### ISSUE TITLE
Doesn't work with Bootswatch and LitElement

### ISSUE THREAD

**Issue by CrazyFlasher** [glromeo/esbuild-sass-plugin#113]
Hi.
I am trying to use [Bootstrap](https://getbootstrap.com/) styles overrided by [Bootswatch](https://bootswatch.com/) styles in **LitElement**

```ts
import {html, LitElement} from "lit";
import {customElement, property} from 'lit/decorators.js';
import styles from '../../../../../../../example/client/s.scss';

@customElement('sign-up-view')
export class LitSignUpView extends LitElement
{
    @property()
    private name?: string = 'World';

    public static override styles = [
        styles
    ];

....
```
**s.scss**
```scss
@import "_variables.scss";
@import "bootstrap/scss/bootstrap.scss";
@import "_bootswatch.scss";
```
**build.ts**
```ts
...
build({
                plugins: [
                    NodeModulesPolyfills(),
                    GlobalsPolyfills({process: true, buffer: true}),
                    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
                    // @ts-ignore
                    sassPlugin({type: "lit-css", cssImports: true})
                ],
...
```
Bootstrap styles successfully loaded and applied, however they are not overrided by Bootswatch styles.
In console there is a warning:
```
@import rules are not allowed here. See https://github.com/WICG/construct-stylesheets/issues/119#issuecomment-588352418.
```
Can you help me please, what I am doing wrong?
Thanks

**Comment by glromeo** [comment]
Clearly an @import has been found in  the resulting css text.
That should be treated as a css @import but constructable stylesheets don't allow those as the message is explaining.
unfortunately I am not familiar with Bootswatch to know where that @import might come from to help...
Such an import would mean that a part of the css was meant to be shared but constructable stylesheet cannot share this way it should be the developer that lists all the shared styles (in the array you pass to styles) to apply to the shadow dom.
I have to close this issue because I don't see anything I can do to help
