### ISSUE TITLE
esbuild-sass-plugin 2.5.0 can not be installed with current esbuild 0.17.7

### ISSUE THREAD

**Issue by doberkofler** [glromeo/esbuild-sass-plugin#121]
When trying to upgrade esbuild-sass-plugin to 2.5.0 npm complains as follows:

```bash
npm ERR! Could not resolve dependency:
npm ERR! peer esbuild@"^0.16.17" from esbuild-sass-plugin@2.5.0
npm ERR! node_modules/esbuild-sass-plugin
npm ERR!   esbuild-sass-plugin@"2.5.0" from the root project
```

**Comment by glromeo** [comment]
Yes, esbuild 0.17 has a significantly different API which requires a refactoring of the plugin and its tests. I will work on it at some point but I don't have the capacity to do it now

**Comment by doberkofler** [comment]
I understand. So basically 2.4.5 is the last version to be used.

**Comment by glromeo** [comment]
This is exactly why I originally wasn't keen on using peer dependencies but at second thoughts this dependency conflict error (there's more than what you just pasted) is telling you that you are using 0.17 which has breaking changes which you shouldn't.
2.5.0 is as good as 2.4.5 but indeed because of the way peer dependencies work you are better off with 2.4.5

**Comment by glromeo** [comment]
v2.6.0 should addresses this issue for good otherwise feel free to reopen this issue

**Comment by martinpitt** [comment]
Confirmed, 2.6.0 works well with esbuild 0.17.10. Thank you!

**Comment by doberkofler** [comment]
No problems now. Thank you!
