### ISSUE TITLE
"No loader configured for .scss" with 2.7.0

### ISSUE THREAD

**Issue by jbrosi** [glromeo/esbuild-sass-plugin#130]
First of all thanks for the great work :)!

I just wanted to report in that starting with 2.7.0 I get the following error when trying to import .scss files form my typescript:

```
 > src/index.tsx:4:7: error: No loader is configured for ".scss" files: src/index.scss
    4 │ import './index.scss';
      ╵        ~~~~~~~~~~~~~~
```
In 2.6.0 it's all working fine.

My sassPlugin configs are as follows:
```
      sassPlugin({
        exclude: /^(https?:\/\/|\/)/,  // ignores http/https: and absolute urls
        transform: postcssModules({
          globalModulePaths: [/@some-global-module/i],
        }),
      }),
```

**Comment by glromeo** [comment]
I see... thank you for this example.
The issue is that in 2.6.0 there was no exclude option (if you had it, it was ignored).
Now is applied but because it's applied at path level your "starting with /" catches all.
I have to fix it because indeed one would expect exclude to apply to the URLs but in the meantime you can either remove exclude altogether or just the / part

**Comment by jbrosi** [comment]
Ohh :D thank you very much for explaining this to me, I remember I had some issues getting "exclude" to work - eventually I found a workaround somewhere else and forgot to remove the option there :)!

Your suggestion works fine for me.
