### ISSUE TITLE
Add support for workspaces when resolving imports

### ISSUE THREAD

**Issue by Minnozz** [glromeo/esbuild-sass-plugin#14]
The current importer finds the first `node_modules` directory and tries to resolve imports in that directory. However, when you use yarn or npm workspaces, a `node_modules` directory may also exist in the parent directory (not sure how many levels) and I believe they should all be tried when resolving an import.

**Comment by Minnozz** [comment]
I'm not sure what the default behaviour is when you don't pass a resolver to sass; maybe it already works in that case? Or maybe you can use `includePaths` instead of doing the resolution yourself? (Not sure if that supports `~tilde` imports).

**Comment by glromeo** [comment]
Hi Bart

> I believe they should all be tried when resolving an import.

You're right and the reason it doesn't is because I opted for a quick and dirty hack to get the path to the sass module
https://github.com/glromeo/esbuild-sass-plugin/blob/9d4ea833709ef871ba11bef27724fe35abeb3344/src/importer.ts#L27
I did that because I thought a full fledged node resolution is a drag for performance... maybe I can give it some thoughts and try and improve it... 

> I'm not sure what the default behaviour is when you don't pass a resolver to sass; maybe it already works in that case?

Nope, unfortunately it would just fail.

> Not sure if that supports ~tilde imports

Going down the route of providing [a full fledged module resolution for sass](https://github.com/glromeo/moderno/blob/master/server/src/util/sass-importer.ts) is laborious and I would like to keep the plugin simple...that said I will try to make it work with yarn workspaces 😉 bear with me

**Comment by Minnozz** [comment]
Thank you!

I've currently found a workaround by passing both `node_modules` paths to the `includePaths` option.
According to https://sass-lang.com/documentation/js-api#importer, `includePaths` are tried after the custom importer, but it seems to work anyway.

**Comment by glromeo** [comment]
@Minnozz v1.4.5 should fix this issue

**Comment by Minnozz** [comment]
I've tried v1.4.5 and unfortunately it didn't work for me. I've taken another look at the importer and I think I simplified the logic to that in #16. Could you take a look?
