### ISSUE TITLE
Prefix classes?

### ISSUE THREAD

**Issue by Zerowalker** [glromeo/esbuild-sass-plugin#144]
I'm wondering if it's possible to prefix classes,
so say you set prefix "foo_",
then the class "bar" would turn into "foo_bar".

The use case is when you don't control all styles so the way to isolate your stylings is to make sure they are unique and also deterministic.

**Comment by glromeo** [comment]
Unfortunately Sass doesn't provide plugins into the parsing process. To do something like that I added the precompile option. You can specify a function that does whatever transformation you want on your files before being compiled by sass.
The function receives the pathname as second argument so that can be used to figure out whether it is a project file then it is just a matter of search and replace for everything starting with a dot.
Note that source mapping is no longer valid when using precompile.
