### ISSUE TITLE
Issue with 3.0.0 & Vite

### ISSUE THREAD

**Issue by greeeg** [glromeo/esbuild-sass-plugin#165]
Hello 👋

Just wanted to let you know that when using this package with v3.0.0 & Vite, I'm getting the following error:
```
[vite] Internal server error: Preprocessor dependency "sass" not found. Did you install it? Try `yarn add -D sass`.
```

Looking at the [release notes](https://github.com/glromeo/esbuild-sass-plugin/releases/tag/v3.0.0), I guess we might need an extra dependency or do something specific to make it work?
Many thanks

**Comment by NathanBeddoeWebDev** [comment]
So esbuild-sass-plugin has changed to use sass-embedded as a dependency, rather than sass. It looks like Vite is looking for specifically the sass dependency. You should `yarn add -D sass` in your package, it sounds like you were relying on esbuild-sass-plugin to install sass for you, which is fragile.

That being said... I'm interested in how you've got Vite and esbuild-sass-plugin working together? From what I know, Vite has first class support for sass and doesn't require the use of another plugin.

**Comment by glromeo** [comment]
Thanks for replying @NathanBeddoeWebDev 
I am looking into trying and providing both sass as default to work on any platform and leave sass-embedded as an option

**Comment by glromeo** [comment]
Please v3.1.0, it should solve this issue
