### ISSUE TITLE
quietDeps does not seem to work, still emits warnings for deps

### ISSUE THREAD

**Issue by jakajancar** [glromeo/esbuild-sass-plugin#17]

**Comment by glromeo** [comment]
Hi @jakajancar thank you for the heads-up... I can see here https://github.com/sass/sass/issues/3065 that this was an issue with dart-sass. I have released v1.4.7 in which I have upgraded sass to 1.35.1. This should fix the issue

**Comment by jakajancar** [comment]
I'm still seeing the warnings:

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($l1 + 0.05, $l2 + 0.05)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
126 │   @return if($l1 > $l2, ($l1 + .05) / ($l2 + .05), ($l2 + .05) / ($l1 + .05));
    │                         ^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_functions.scss 126:25  contrast-ratio()
    node_modules/bootstrap/scss/_functions.scss 108:22  color-contrast()
    src/theme/_badge.scss 32:12                         @import
    src/theme/_theme.scss 18:9                          @import
    src/main.scss 11:9                                  root stylesheet
```

:/

**Comment by glromeo** [comment]
That might be because [as per sass docs](https://sass-lang.com/documentation/js-api#quietdeps)

>Stylesheets that are imported relative to the entrypoint are not considered dependencies.

[I was able to silence the warnings](https://github.com/glromeo/esbuild-sass-plugin/commit/a2cf9c9366563dc20d919839ca3bf0aa9d36fe97) and now my tests don't show any even with bootstrap

Have a look at this example

https://github.com/glromeo/esbuild-sass-plugin/blob/a2cf9c9366563dc20d919839ca3bf0aa9d36fe97/test/fixture/bootstrap/entrypoint.scss#L3
