### ISSUE TITLE
[version 1.6.1] Error: Do not know how to load path: sass:/path/to/_file.scss

### ISSUE THREAD

**Issue by n19htz** [glromeo/esbuild-sass-plugin#31]
After upgrading to v1.6.1 getting error in the title for all scss file imports

**Comment by n19htz** [comment]
> Hi @n19htz do you have a project that helps me reproduce this issue?

basically, I got custom path resolver plugin for esbuild. This plugin conditionally resolves path for .scss files and in onResolve hook forwards it to esbuild-sass-plugin for further processing, i e
```
build.onResolve({ filter: /\.scss$/ }, args => {
    ...
    return { path: resolvedPath, namespace: 'sass' }
})
```

on version < 1.6.0 it works like a charm, but after 1.6.0 its broken

**Comment by glromeo** [comment]
I am investigating the direction to take with the plugin to make the resolution more flexible and you are actually giving me a good idea on how to do so without putting the burden on the plugin!

Essentially breaking down the plugin into a resolver and a loader...

I will probably have to change the namespace naming logic but I will likely make it explicit so that you can give a namespace to a loader and you know that he will handle that.
