### ISSUE TITLE
additionalData option like in sass-loader?

### ISSUE THREAD

**Issue by jjant** [glromeo/esbuild-sass-plugin#40]
Hi, I'm trying to understand if I can do something like 
```js
const sassLoaderOptions = { additionalData: `$env: ${process.env.NODE_ENV};` }
``` 
which sass-loader allows: https://www.npmjs.com/package/sass-loader#additionaldata, we use this for filling in that variable in dev and use custom styles there.

**Comment by glromeo** [comment]
sass-loader loads the contents of the sass file in the Javascript host which is something I don't want to do with the plugin because I want the communication between the plugin and the sass implementation to be as lean as possible so that I can use worker threads and possibly the embedded sass protocol when it's going to be mature enough (and if fast enough).

that said you can achieve something similar like this:

**build.js**
```javascript
const esbuild = require("esbuild");
const {sassPlugin} = require("esbuild-sass-plugin");

esbuild
    .build({
        entryPoints: ["index.js"],
        outdir: "./out",
        bundle: true,
        plugins: [
            sassPlugin({
                importer(url) {
                    if (url === "..") {
                        return {contents: `
                            $color: ${"blue"};
                        `}
                    }
                    return null;
                }
            })
        ]
    })
    .then(console.log)
    .catch(console.error);
```
**index.js** (entrypoint)
```javascript
import "./index.scss";
```
**env.scss** (to trick the IDE into thinking that element 'color' is resolved only by name without use of explicit imports)
```scss
$color: red;
```
**index.scss**
```scss
@import "..";

body {
  color: $color;
}
```

Note the use of "..". It's crazy but it's the only way I can think of to have an import path that's valid yet not resolved internally by sass and hence delegated to the importer.
