### ISSUE TITLE
feature:  sass global variable  

### ISSUE THREAD

**Issue by Carrie999** [glromeo/esbuild-sass-plugin#47]
like the webpack loader sass-resources-loader

**Comment by glromeo** [comment]
Is this https://github.com/glromeo/esbuild-sass-plugin/issues/40 that you are talking about?

**Comment by glromeo** [comment]
@Carrie999 there's 2.0.0-alpha.0 in npm which has some breaking changes but amongst them there's the capability 
to do something like what you ask...
It's in alpha because at the moment it doesn't respect source maps...I need to fix that but, in the meanwhile, it's usable
if you want to experiment with it.

```javascript

const globals = require("./globals.sass")

...

plugins: [
      sassPlugin({
        precompile: (source, pathname) =>`
           ${globals}
           ${source}
        `
      })
    ]
```

**Comment by glromeo** [comment]
The v2.x branch has this feature and it's covered by tests, closing this issue
