### ISSUE TITLE
nonce global issue

### ISSUE THREAD

**Issue by rhu25** [glromeo/esbuild-sass-plugin#76]
Hi Gianluca,

thanks for your update for nonce previously. we have another a issue with nonce

we use esbuild-sass-plugin like this,

app A has app B as dependency, app B used esbuild-sass-plugin to esbuild.

following code is app B code
```
esbuild.build({
  entryPoints: ['src/index.ts'],
  outdir: 'dist/esm',
  bundle: true,
  sourcemap: true,
  minify: true,
  splitting: true,
  format: 'esm',
  target: 'esnext',
  plugins: [nodeExternalsPlugin(), sassPlugin({
    type: 'style',
  })],
})
```
since nonce need to be dynamic for each app used app B.
we cant just hardcoded nonce like this 
```
esbuild.build({
  entryPoints: ['src/index.ts'],
  outdir: 'dist/esm',
  bundle: true,
  sourcemap: true,
  minify: true,
  splitting: true,
  format: 'esm',
  target: 'esnext',
  plugins: [nodeExternalsPlugin(), sassPlugin({
    type: 'style',
    nonce:'12345'
  })],
})
```

so is possible to fix [this line](https://github.com/glromeo/esbuild-sass-plugin/blob/main/src/utils.ts#L102) (if nonce not pass) to 
```
style.setAttribute("nonce", window.__esbuild_nonce__);
```

so in this way its very easy to config in app A, just add 
```
window.__esbuild_nonce__ = "dynamic_12345"
```

since i cant find __esbuild_nonce__ in esbuild, so i just make this variable up, but webpack has `__webpack_nonce__`

thanks

@glromeo

**Comment by glromeo** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/7e3bc453-64fb-4a34-bcaa-481724e5d3d9-774bf184-bc1c-4f48-a627-8361720afa10-v1.png?transparent=1&palette=1&width=246)

I rather not pollute the window scope for that... 

How about we make so that you can bundle AppB leaving nonce unresolved and then bundle AppA using define?

In theory, this means you need to have two build target for your AppB one for when you want to use it standalone (if you do) and one for when it has to be re-bundled in AppA.

Suppose you pass in AppB build
```
{
  "nonce": "__whatever__"
}
```
then it leaves `__whatever__` accessed globally and unresolved. (call it `__esbuild_nonce__` if you prefer, assume the code will just look at the string starting with `__`).
 
 At this point you can specify `window.__whatever__ = "1234..."` and that would work as you intended, but you can also
 just bundle AppA passing `define: { "__whatever__": "1234..." }` and that avoids polluting the global scope.

**Comment by rhu25** [comment]
it works for me thank you very much

**Comment by rhu25** [comment]
Hi Gianluca,

I created a new issue for esbuild,
https://github.com/glromeo/esbuild-sass-plugin/issues/79

Thanks,
Ran

RAN HU ***@***.***>于2022年3月29日 周二10:08写道：
