### ISSUE TITLE
Using the "sass" field in package.json

### ISSUE THREAD

**Issue by tleunen** [glromeo/esbuild-sass-plugin#82]
The sass-loader in webpack does read the field `sass` and `style` in package.json before reading `main` for a node_modules package. Would it be possible to have the same feature in the plugin?

In other words, having `@import "MyPackage";` would try to resolve with the file in the "sass" field if it exists before using `main`.

**Comment by glromeo** [comment]
@tleunen 2.3.0 now allows you to specify ```prefer: "sass"``` that does what you want.
Due to some limitations the resolution takes place only if the import is prefixed with `~` though!
I am investigating on the possibility of rewriting the importer and get rid of this limitation
but I don't have much time at hand right now so I don't know when and if that will happen

**Comment by tleunen** [comment]
Thank you so much @glromeo :)
