### ISSUE TITLE
`type: 'css'` ignored when using CSS modules

### ISSUE THREAD

**Issue by eidellev** [glromeo/esbuild-sass-plugin#93]
Hi and thanks for making this  plugin. It's just what I needed.

When I'm using CSS modules the result will always be embedded in the JS bundle like so:
```javascript
// src/basic/Box/Content/Content.module.scss
var css3 = `/* INSIGHTS-3 COLOR SCHEME */
/* INSIGHTS-3 COLOR SCHEME */
/* General Elements */
/* Sentiment */
/* Form Inputs */
/* Widgets */
/* Sidebar */
.Content-module__content___Hm6Xg.Content-module__standardPadding___q6C3U {
  padding: var(--padding-narrow);
}`;
document.head.appendChild(document.createElement("style")).appendChild(document.createTextNode(css3));
```

And here is my config: 
```javascript
sassPlugin({
  type: 'css',
  sourceMap: true,
  transform: postcssModules({
    generateScopedName: '[name]__[local]___[hash:base64:5]',
  }),
  filter: /.module.scss$/,
}),
sassPlugin({
  type: 'css',
  sourceMap: true,
  filter: /.scss$/,
}),
```

**Comment by glromeo** [comment]
`css` modules are `javascript` modules and they have to be passed to esbuild using the `js` loader hence the plugin output is bypassed altogether

sorry @eidellev although conceptually one could pass `esbuild` the module and still write the css text I don't want the plugin to have to directly write on the file system because this is responsibility of `esbuild` who decides where the output goes etc

**Comment by eidellev** [comment]
thank you for clarifying that @glromeo

**Comment by glromeo** [comment]
@eidellev v2.7.0 finally introduces a solution for this issue without having to write to the file system... please have a look if still interested

**Comment by eidellev** [comment]
thanks @glromeo !
it's a little late for me, but I appreaciate the effort.
