### ISSUE TITLE
Use esbuild's resolve function as an Importer for sass

### ISSUE THREAD

**Issue by sgarfinkel** [glromeo/esbuild-sass-plugin#94]
This would allow users to override (such as with aliases) the default sass resolution. Webpack's `sass-loader` basically implements this pattern, and delegates responsibility for resolution to the build tool: https://github.com/webpack-contrib/sass-loader/blob/master/src/utils.js#L653-L678. 

I also suspect that esbuild's resolution is more efficient than the default one in sass. For my use-case, I'm dealing with legacy imports that were designed with Webpack's sass-loader and use `~` to mean "resolve against node_modules (either local if possible, root if not)". I can do this already by directly supplying my own `FileImporter` via the options object, but I'd much prefer to implement this as an `onResolve` callback.

Currently, I can't actually implement this with any workaround because the `PluginBuild` object, which has the `resolve` function isn't surfaced anywhere to the user: https://github.com/glromeo/esbuild-sass-plugin/blob/main/src/plugin.ts#L38

Sadly this probably would require using the Legacy API, in order to get the resolveDir. The modern Importer API doesn't surface the file being _processed_.

**Comment by glromeo** [comment]
@sgarfinkel I would have liked to use esbuild's resolve function but it is async, it wouldn't work

**Comment by glromeo** [comment]
I closed the issue because it is not an issue, this would have been better off as a discussion on the possibility of adding the option to also use the async mode to the dart sass compileString call.
I wouldn't want to just replace the compileString with the async version because the disclaimer that mentions the performance being likely worse. 
Yet, at second thoughts, if it wasn't for the fact that the documentation is confusing and it would require me some time to experiment with async importers and see if they actually work (time which I don't have at the moment) there could be async/sync modes with just a flag switch.
If you want to fork the project and experiment in that direction then changing the plugin for passing the onResolve would be trivial.
I would be happy to merge such changes

**Comment by sgarfinkel** [comment]
Sure. I’m curious if using the embedded sass plus the async compile function would give you better performance. I’ve seen the warning about the asynchronous functions being much slower but the docs don’t actually provide any benchmarks.

**Comment by sgarfinkel** [comment]
The other option would be to make this opt-in via a parameter so that by default the synchronous blocking compilation is used.

**Comment by glromeo** [comment]
The embedded sass is not the answer https://github.com/glromeo/esbuild-sass-plugin/pull/68

Out of curiosity I just spiked a search and replace of sync for async and without any further change 
the results are in par with the sync version but just with my synthetic benchmark that doesn't rely heavily 
on sass itself but mostly on many quick turnarounds js<->sass

BUT...

Let's put aside for a moment the question whether have async/sync compile or just async then there's the question
of how to "just use" esbuild resolution.
Suppose you have the resolve available, then? Don't forget that esbuild doesn't implement the full fledged sass module resolution (i.e. trying different ext and looking at sass entries in package.json).
I am afraid we have been a bit delusional (and I include me because I was thinking along the same lines)

Now, understood that we have to stop daydreaming about esbuild's resolve. What is that the resolve capabilities provided by the plugin (especially when using browserify's package) don't provide you?
https://github.com/glromeo/esbuild-sass-plugin/blob/b686782ce97d4bfd3db76e63e7ea6e9e2e771caa/src/render.ts#L103
this should cater for the legacy ~ imports

Anyway... happy to help if you spot a corner case not implemented 
in which case create a GitHub repo reproducing the issue and I will take it from there
