### ISSUE TITLE
Importing node_modules style

### ISSUE THREAD

**Issue by eoikonomou** [glromeo/esbuild-sass-plugin#98]
This might not be an issue of the plugin but my own fault. 
I am trying to use the plugin since I am using sass in my project and I am stuck with some import files.

In my main style I am importing `~bootstrap/dist/css/bootstrap.min.css`. I set `cssImports` to `true` but I am still not able to make this work since the application tries to fetch the css file from `node_modules` path instead of being part of the output bundle file. 

It was my understanding that the styles would be added in the bundle file. Instead it seems like I have to add the `node_modules` folder in the build destination so that it can be reachable for this import.

Is there an option that I did not see that I need to use in order for the import to be processed and injected to the bundle?

My `plugins` section in the `build.js` file looks like this:

![image](https://user-images.githubusercontent.com/12374962/196100729-865b5395-33e2-4e43-bf0b-5f8d7f8b9c74.png)

**Comment by glromeo** [comment]
hmm... this is a funny issue because from one side is yet another case of conflicting options (sorry about that!)
while from another side is simply an understandable mistake done by adding the `.css` extension!


If you follow the SASS documentation or [if you just refer to this Stack Overflow post](https://stackoverflow.com/questions/7111610/import-regular-css-file-in-scss-file) 
you'll find the explanation you are after. 


But since I am at it, let me clarify that when one is opting for `style` modules the plugin wraps everything sass produces and that's it. `esbuild` won't do anything else hence that `cssImports` is ignored, it only happens when type is `css`.
Luckily for you sass, as explained above, can do the inclusion of the import, you can remove that misleading option and happy days!

**Comment by eoikonomou** [comment]
Thank you for your reply. I did go through the SASS documentation as you proposed and indeed it was as simple as replacing `@import` with `@use`. 

Just wanted to leave this here in case someone else end up here looking for an answer. 

Thanks again!
